-- 코드를 입력하세요
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') as PUBLISHED_DATE
from BOOK 
where TO_CHAR(PUBLISHED_DATE,'YYYY-MM-DD') > '2021-01-01' and CATEGORY = '인문'
order by PUBLISHED_DATE asc
;