-- 코드를 입력하세요
-- 2022년 10월에 작성된 게시글 제목(A.TITLE), 게시글 ID(A.BOARD_ID), 
-- 댓글 ID(B.REPLY_ID), 댓글 작성자 ID(B.WRITER_ID), 댓글 내용(B.CONTENTS), 
-- 댓글 작성일(B.CREATED_DATE)을 조회하는 SQL문

SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A , USED_GOODS_REPLY B 
WHERE A.BOARD_ID = B.BOARD_ID
    and TO_CHAR(A.CREATED_DATE,'YYYY-MM') ='2022-10'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;